init:
    data: true
spring:
    datasource:
      url: jdbc:h2:file:./db;DB_CLOSE_ON_EXIT=FALSE
    jpa:
        hibernate:
            ddl-auto: update
    cache:
        cache-names: deleted_product
    mvc:
        format:
            date-time: iso