init:
    data:
        enabled: true
spring:
    datasource:
      url: jdbc:h2:file:./db;DB_CLOSE_ON_EXIT=FALSE
    jpa:
        hibernate:
            ddl-auto: update
    cache:
        cache-names: deleted_product
    data:
        rest:
            base-path: /api
    mvc:
        format:
            date-time: iso